### PR TITLE
[MWPW 151457] Added stage domains map to make links environment-aware

### PR DESCRIPTION
**Pull request by robert-bogos**
**Description**
This PR adds the `stageDomainsMap` to the config allowing links to be environment-aware.
More about this new feature can be found in [here](https://github.com/orgs/adobecom/discussions/2437).

Resolves: [MWPW-151457](https://jira.corp.adobe.com/browse/MWPW-151457)

Test URLs:
Before: https://main--cc--adobecom.hlx.page/drafts/rbogos/default?martech=off&georouting=off
After: https://main--cc--aishwaryamathuria.hlx.page/drafts/rbogos/default?martech=off&georouting=off&milolibs=mwpw-146056-stage-links--milo--robert-bogos

### CODE REVIEW

**Review by aishwaryamathuria — APPROVED** [review]

**Comment by aishwaryamathuria** [comment]
@robert-bogos Could you add the before after urls so that aem checks succeed as PR cannot be merged if this check if aem-psi-check is failing

**Review by salonijain3 — APPROVED** [review]

**Review by Ruchika4 — APPROVED** [review]

**Comment by spadmasa** [comment]
Hi @robert-bogos , can you please confirm on the after url to be verified   , not able to load any of the product page url with milolibs , 
https://mwpw-146056-stage-links--milo--robert-bogos.hlx.page/drafts/rbogos/default?martech=off&georouting=off
https://mwpw-146056-stage-links--milo--robert-bogos.hlx.page/products/photoshop?martech=off&georouting=off

**Comment by robert-bogos** [comment]
Hi @spadmasa ! I think the solution for this is the same as I stated [in here](https://github.com/adobecom/cc/pull/340#issuecomment-2177962262).

**Comment by Ruchika4** [comment]
An issue has been reported for stage mapping on bacom and their PR is reverted. Jira ticket https://jira.corp.adobe.com/browse/MWPW-153603
@robert-bogos please confirm if we should go ahead and close this PR for now. I am adding don not merge label for now.

cc @salonijain3  @dstrong23 @spadmasa

**Comment by robert-bogos** [comment]
@Ruchika4 There will be an enhancement coming to handle the bacom use case. The feature works as expected in converting links based on the config map. Currently is up to each consumer to decide if this is advantageous or not.

**Comment by Ruchika4** [comment]
> @Ruchika4 There will be an enhancement coming to handle the bacom use case. The feature works as expected in converting links based on the config map. Currently is up to each consumer to decide if this is advantageous or not.

Apologies for late reply @robert-bogos . I was on PTO. Could you please fix the psi check failure issue. @spadmasa could you please help verify it once. We have another issue reported here https://jira.corp.adobe.com/browse/CCWT-24022 which needs this fix

cc @dstrong23 @salonijain3

**Comment by spadmasa** [comment]
Hi @Ruchika4  , We need the after url to test as with  the urls provided in the  Pr we were not able to verify any of our product page

**Comment by Ruchika4** [comment]
As discussed with @robert-bogos closing this PR and creating a duplicate PR to fix the psi check failure and test issue here
https://github.com/adobecom/cc/pull/362

**Pull request closed without merging**
