### PR TITLE
[hue saturation] upload image icon authored is not seen visible in mobile mode

### PR DESCRIPTION
**Pull request by suhjainadobe**
[hue saturation] upload image icon authored is not seen visible in mobile mode

Resolves: [MWPW-146219](https://jira.corp.adobe.com/browse/MWPW-146219)

**Test URLs:**
- Before: https://main--cc--adobecom.hlx.live/drafts/suhjain/document7?martech=off
- After: https://mwpw-146219--cc--adobecom.hlx.live/drafts/suhjain/document7?martech=off

### CODE REVIEW

**Comment by aishwaryamathuria** [comment]
@suhjainadobe There is no blue border on mobile on upload button tap

**Comment by suhjainadobe** [comment]
> @suhjainadobe There is no blue border on mobile on upload button tap

done

**Comment by aishwaryamathuria** [comment]
@suhjainadobe The correct button style is not applied if interactive-holder is light The button should be white with dark outline
Screenshot 2024-04-11 at 1 20 59 PM

**Review by aishwaryamathuria — APPROVED** [review]

**Review by drashti1712 — APPROVED** [review]

**Comment by spadmasa** [comment]
Validation done on the below pr :
https://mwpw-146219--cc--adobecom.hlx.live/drafts/suhjain/document7?martech=off
image
image
image

https://mwpw-146219--cc--adobecom.hlx.page/drafts/Souj/interactivelements/heusat
image

image
image

image

image
image

**Pull request merged**
