### PR TITLE
MWPW-159427: Milo Catalog: Ipad specific issues

### PR DESCRIPTION
**Pull request by mirafedas**
On iOS version 15 and lower there is a different way of managing the vertical stacking context, which puts the modal below the merch card. Adding z-index on the merch-sidenav resolves this problem.

Related Milo PR: https://github.com/adobecom/milo/pull/2994

Resolves: [MWPW-159427](https://jira.corp.adobe.com/browse/MWPW-159427)

**Test URLs:**
- Before: https://main--cc-–adobecom.hlx.live/products/catalog?martech=off
- After: https://mwpw-159427-ipad-issues --cc-–adobecom.hlx.live/products/catalog?martech=off (added a space to hide the link from PSI check)

For PSI check:
https://mwpw-159427-ipad-issues--milo--mirafedas.hlx.live/?martech=off&georouting=off

### CODE REVIEW

**Comment by Axelcureno** [comment]
why is the only change is in minified file?

**Comment by mirafedas** [comment]
> adobecom/milo#2994

@Axelcureno every time when we make a change in merch-sidenav on Milo, we need to update the minified merch-sidenav in CC to keep it up to date. Here is the respective Milo PR: https://github.com/adobecom/milo/pull/2994

**Review by 3ch023 — APPROVED** [review]

**Review by bozojovicic — APPROVED** [review]

**Review by yesil — COMMENTED** [review]
Can you clarify why merch-sidenav is still needed on cc w.r.t https://github.com/adobecom/cc/pull/412#pullrequestreview-2351873556 ?

**Comment by mirafedas** [comment]
Closing because the needed change will be added in the https://github.com/adobecom/cc/pull/412

**Pull request closed without merging**
