### PR TITLE
[MWPW-147305] Adding generative pattern label to generate bar on Interactive Marquee

### PR DESCRIPTION
**Pull request by suhjainadobe**
Adding generative pattern label to generate bar on Interactive Marquee

Resolves: [[MWPW-147305]](https://jira.corp.adobe.com/browse/MWPW-NUMBER)

**Test URLs:**
- Before: https://main--cc--adobecom.hlx.page/drafts/suhjain/interactive-marquee/nothern-lights
- After: https://generatelabel--cc--suhjainadobe.hlx.page/drafts/suhjain/interactive-marquee/nothern-lights

### CODE REVIEW

**Comment by aishwaryamathuria** [comment]
@suhjainadobe Could update branch and add reviewrs if this PR is ready for review ?

**Review by aishwaryamathuria — CHANGES_REQUESTED** [review]
@suhjainadobe Could update branch and add reviewers if this PR is ready for review ?
Also could you fix the lint issues and test urls in this PR.

**Comment by Ruchika4** [comment]
@suhjainadobe , please update the test url to hlx.live psi checks are failing.

**Comment by suhjainadobe** [comment]
Closing for now, will reopen it after adding the changes for subsequent changes as well.

**Pull request closed without merging**
