### PR TITLE
MWPW-142006 - Enable repo-sync for graybox

### PR DESCRIPTION
**Pull request by arshadparwaiz**
* Enable CC repo-sync for CC graybox repo

Resolves: [MWPW-142006](https://jira.corp.adobe.com/browse/MWPW-142006)

### CODE REVIEW

**Review by Ruchika4 — APPROVED** [review]

**Review by sukamat — APPROVED** [review]

**Review by aishwaryamathuria — APPROVED** [review]

**Comment by salonijain3** [comment]
@arshadparwaiz If this ready to be merged to stage, can you add the "ready for stage" label, does it need verification or is a trivial change? 
IF it needs verification, please add the label and ask someone to verify and they will add the "verified" label. 
The process is mentioned in https://github.com/adobecom/cc/wiki

**Comment by sukamat** [comment]
@salonijain3 This cannot be verified before merging as it runs within github. That said, it has been validated in bacom repo. A copy of that script is now being created in other repos. Hope that provides some context.
https://github.com/adobecom/bacom/pull/191

**Comment by aishwaryamathuria** [comment]
@sukamat Could you confirm if this PR can be merged in main or if it needs some verification to be done before merging to main?
If It can be merged in main could you add "Ready for main" label
CC: @salonijain3

**Comment by sukamat** [comment]
@arshadparwaiz could you validate the action and set the label as requested ?

**Comment by arshadparwaiz** [comment]
This github workflow is verified and working fine.
https://github.com/adobecom/cc/actions/runs/8653039191/job/23727321412
cc: @aishwaryamathuria @salonijain3 @sukamat

**Pull request merged**
