### PR TITLE
acomsis cookie logic for cn homepage

### PR DESCRIPTION
**Pull request by seanchoi-dev**
Resolves: [MWPW-151792](https://jira.corp.adobe.com/browse/MWPW-151792)

**Test URLs:**
- Before: https://stage--cc--adobecom.hlx.live/careers?martech=off
- After: https://acomsis-cookie--cc--adobecom.hlx.live/careers?martech=off

Things about this implementation,
- This logic is to add / remove `acomsis` cookie according to the user login status.
- User can login / logout outside of a.com, loading IMS is required to check the status.
- The logic has been reviewed and finalized with many engineers and other stakeholders both from Milo and Dexter.
- This logic has to hit before loading blocks, so users can't see the flicker. (Cannot be running as a block)
- Akamai will redirect according to the `acomsis` cookie.
-- If the cookie exists, all users visiting logged-out homepage should get redirected to signed-in homepage.
-- If the cookie doesn't exists, all users visiting logged-in homepage should get redirected to signed-out homepage.
- All other locales except `cn`'s logged out homepage is under milo homepage repo and logged-in homepage is currently under Dexter and they both have this logic. (and a bit more stuff in it)
-- https://github.com/adobecom/homepage/blob/stage/homepage/scripts/scripts.js#L239
- New Chinese signed-in homepage is under CC repo and missing this logic therefore it causes a major bug that CN users can visit logged in homepage without logged in and once they logged in they can't revisit logged out page even after logged out.
- Akamai side for this logic is ready on stage for testing
-- [WPS-25719](https://jira.corp.adobe.com/browse/WPS-25719)
- We will need a decent QA on stage and we can't do it because this PR isn't merged into stage, yet. There are also pressures from above.
-- This doesn't mean we need to approve and merge blindly but we want to review this quickly.

Let me know if you have any questions about this PR.

### CODE REVIEW

**Comment by aishwaryamathuria** [comment]
@seanchoi-dev We are checking for the signed in user at the start of the script and during this time the whole page rendering is blocked till ims returns the result which is going to have a performance impact on the CC pages. 
Can we do it as a delayed processing? 
@amitbikram @salonijain3 Could you share your inputs on the same?

**Comment by seanchoi-dev** [comment]
> @seanchoi-dev We are checking for the signed in user at the start of the script and during this time the whole page rendering is blocked till ims returns the result which is going to have a performance impact on the CC pages. Can we do it as a delayed processing? @amitbikram @salonijain3 Could you share your inputs on the same?

There is no other option than checking IMS before rendering anything.
And that's the way how homepage works now.

 imslib.min.js is about 17kb and as long as we don't exceed 100kb total byes before loading LCP, we will get proper LH score for LCP.
 
 I limited this logic only for the homepage path so it doesn't affect existing CC pages.
 Let me know if you have question why we need this.

**Comment by amitbikram** [comment]
@seanchoi-dev script.js is the bootstrap file which loads for all the pages, we should keep it lightweight and should avoid(if possible) adding any additional logic that is required for one/few pages. We should think of an alternative aproaches to handle this. Below few options I can think of right now:

- Can we go with Akamai approach to serve /cn/creativecloud/roc/home from homepage
- A redirect Milo block with current cookie and redirection logic which can be used in the page where we need it.
cc: @salonijain3 @aishwaryamathuria

**Comment by seanchoi-dev** [comment]
> @seanchoi-dev script.js is the bootstrap file which loads for all the pages, we should keep it lightweight and should avoid(if possible) adding any additional logic that is required for one/few pages. We should think of an alternative aproaches to handle this. Below few options I can think of right now:
> 
> * Can we go with Akamai approach to serve /cn/creativecloud/roc/home from homepage
> * A redirect Milo block with current cookie and redirection logic which can be used in the page where we need it.
>   cc: @salonijain3 @aishwaryamathuria

I understand that script.js is getting loaded all pages and we want to keep it lightweight as much as possible.
I moved the function at utils.js though, utils.js is also getting loaded everywhere as well, I hope this makes us feel better.

Things about this implementation,
- This logic is to add / remove `acomsis` cookie according to the user login status.
- User can login / logout outside of a.com, loading IMS is required to check the status.
- The logic has been reviewed and finalized with many engineers and other stakeholders both from Milo and Dexter.
- This logic has to hit before loading blocks, so users can't see the flicker. (Cannot be running as a block)
- Akamai will redirect according to the `acomsis` cookie.
-- If the cookie exists, all users visiting logged-out homepage should get redirected to signed-in homepage.
-- If the cookie doesn't exists, all users visiting logged-in homepage should get redirected to signed-out homepage.
- All other locales except `cn`'s logged out homepage is under milo homepage repo and logged-in homepage is currently under Dexter and they both have this logic. (and a bit more stuff in it)
-- https://github.com/adobecom/homepage/blob/stage/homepage/scripts/scripts.js#L239
- New Chinese signed-in homepage is under CC repo and missing this logic therefore it causes a major bug that CN users can visit logged in homepage without logged in and once they logged in they can't revisit logged out page even after logged out.
- Akamai side for this logic is ready on stage for testing
-- [WPS-25719](https://jira.corp.adobe.com/browse/WPS-25719)
- We will need a decent QA on stage and we can't do it because this PR isn't merged into stage, yet. There are also pressures from above.
-- This doesn't mean we need to approve and merge blindly but we want to review this quickly.

Let me know if you have any questions about this PR.

**Comment by amitbikram** [comment]
@seanchoi-dev We wont get much benefit moving it to utils as the approach remains same. Since this is for one specific page lets with with the current approach to keep it simple. We may need to revisit if this applies to more pages or see any side effect at later stage. Approving it for now. Thanks!
cc: @salonijain3 @aishwaryamathuria

**Review by amitbikram — APPROVED** [review]

**Review by aishwaryamathuria — APPROVED** [review]

**Pull request merged**
