### PR TITLE
[MWPW-158382] Trying to merge the common scripts for performance improvement

### PR DESCRIPTION
**Pull request by drashti1712**
* This PR merges the CC utils.js into scripts.js to improve page performance
* **Please note: Once this PR is merged, we would immediately need to update the preloads in headers.xlsx as utils.js will be removed.**

Resolves: [MWPW-158382](https://jira.corp.adobe.com/browse/MWPW-158382)

**Test URLs:**
- Before: https://only-preload--cc--adobecom.hlx.live/drafts/drashti/ps-performance/photoshop?martech=off
- After: https://merge-utils--cc--adobecom.hlx.live/drafts/drashti/ps-performance/photoshop?martech=off

### CODE REVIEW

**Comment by spadmasa** [comment]
Do not see our product page url loading with the milolibs , please confirm on this 
https://merge-utils--cc--adobecom.hlx.live/products/premiere?martech=off&mep=off
https://merge-utils--cc--adobecom.hlx.live/products/illustrator
https://merge-utils--cc--adobecom.hlx.live/products/photoshop/online
https://merge-utils--cc--adobecom.hlx.live/products/catalog
https://merge-utils--cc--adobecom.hlx.live/products/photoshop/explore
https://merge-utils--cc--adobecom.hlx.live/products/photoshop/edit-photos
https://merge-utils--cc--adobecom.hlx.live/products/photoshop/remove-background

**Comment by aishwaryamathuria** [comment]
@drashti1712 Could you also make the change to add styles.css in head html in place of loading it dynamically in scripts.. We can then update the headers and run tests together for both

**Review by aishwaryamathuria — CHANGES_REQUESTED** [review]
@drashti1712 Could you also make the change to add styles.css in head html in place of loading it dynamically in scripts.. We can then update the headers and run tests together for both

**Review by aishwaryamathuria — CHANGES_REQUESTED** [review]
There are still references of utils js in interactive metadata js file

**Comment by aishwaryamathuria** [comment]
Closing this PR as these changes are causing cyclic dependency issue.. Please open a new PR with the discussed changes

**Pull request closed without merging**
