### PR TITLE
MWPW-143894, MWPW-142148 sidenav authoring enhancements

### PR DESCRIPTION
**Pull request by npeltier**
MWPW-143894 resolution proposal to limit authoring errors in sidenav update vs categories
MWPW-142148 allow icons in parent categories

[typical sidenav](https://143894--cc--npeltier.hlx.live/drafts/npeltier/sidenav-test?martech=off) and now [sidenav with icons](https://143894--cc--npeltier.hlx.live/drafts/npeltier/sidenav-test-icons?martech=off)
(not putting those URLs for PSI check as sidenav should never be placed as LCP)

Resolves: 
- [MWPW-143894](https://jira.corp.adobe.com/browse/MWPW-143894)
- [MWPW-142148](https://jira.corp.adobe.com/browse/MWPW-142148)

**Test URLs:**
- Before: https://main--cc--adobecom.hlx.live/careers?martech=off
- After: https://143894--cc--npeltier.hlx.live/careers?martech=off

### CODE REVIEW

**Comment by npeltier** [comment]
exact same code as what was initially presented in https://github.com/adobecom/cc/pull/245 before my local stage branch got crushed

**Review by 3ch023 — APPROVED** [review]

**Review by aishwaryamathuria — APPROVED** [review]

**Comment by afmicka** [comment]
@npeltier reordering categories does not work with these changes. Could you please check?

**Comment by aishwaryamathuria** [comment]
@npeltier Could you check the PSI score? It is currently failing.
CC: @salonijain3

**Comment by aishwaryamathuria** [comment]
> @npeltier Could you check the PSI score? It is currently failing. CC: @salonijain3

@npeltier Could you review the failure in PR checks?
CC: @salonijain3 @dstrong23 @Ruchika4

**Comment by salonijain3** [comment]
This PR is stale and was open > 2 weeks, closing this PR. Please feel free to open another PR if needed.

**Review by salonijain3 — APPROVED** [review]

**Pull request merged**
