### PR TITLE
[MWPW-158444] Added stage domains map

### PR DESCRIPTION
**Pull request by aishwaryamathuria**
< @robert-bogos opening this PR from https://github.com/robert-bogos/cc/pull/1 >
This PR adds the stageDomainsMap, enabling the conversion of production URLs to their stage equivalents in the stage environment.
More details about this feature can be found in [this discussion](https://github.com/orgs/adobecom/discussions/2880).

Resolves: [MWPW-158444](https://jira.corp.adobe.com/browse/MWPW-158444)

Test URLs:

Before: https://main--cc--adobecom.hlx.live/careers?martech=off
After: https://mwpw-158444-domains-map--cc--adobecom.hlx.live/careers?martech=off

### CODE REVIEW

**Review by salonijain3 — APPROVED** [review]

**Review by Ruchika4 — APPROVED** [review]

**Comment by robert-bogos** [comment]
Hi @spadmasa ! I've updated the current `stageDomainsMap` to preserve the behaviour you're talking about

**Review by robert-bogos — APPROVED** [review]
👍

**Comment by spadmasa** [comment]
Validation done in below urls after the approvals links are seen pointing to stage for other domains
https://mwpw-158444-domains-map--cc--adobecom.hlx.page/products/firefly
https://mwpw-158444-domains-map--cc--adobecom.hlx.live/products/firefly
https://mwpw-158444-domains-map--cc--adobecom.hlx.page/creativecloud
{79F37CCF-880D-4542-BFB7-F223C01017F8}
{CB02326D-CCE7-4AC8-92B0-DB9B8677B9D3}
{F927D095-9684-463A-90D0-3CD8EA435FBC}

{315A14C8-8DF2-43BF-9A8C-4A0729ECF012}
{54F0C5D1-E29F-4446-8A4B-DADA43A2E080}

Do not see it working for business.adobe.com @aishwaryamathuria  @robert-bogos  can you please check
https://mwpw-158444-domains-map--cc--adobecom.hlx.page/products/firefly
{1B244FDF-95B9-43CB-AB75-9D15D5A24F9D}


CC : @sigadamvenkata  , @salonijain3 , @dstrong23 , @Ruchika4 , @narcis-radu

**Comment by spadmasa** [comment]
Validation done in business.adobe.com as well see the stage domain links coming now
https://mwpw-158444-domains-map--cc--adobecom.hlx.page/products/firefly
{5292AD52-9FA2-4681-B85A-E7BF9121FE6F}
{C5B3249C-7196-44EF-BDBF-7EAF417E2EB1}

**Pull request merged**
