### PR TITLE
MWPW-157468 flipping again sidenav and collection

### PR DESCRIPTION
**Pull request by npeltier**
allow easier keyboard browsing of catalog page 

Test URLs:

Before: https://main--cc--adobecom.hlx.live/?martech=off
After: https://mwpw-157468--cc--npeltier.hlx.live/?martech=off

### CODE REVIEW

**Review by seanchoi-dev — APPROVED** [review]

**Review by aishwaryamathuria — APPROVED** [review]

**Comment by aishwaryamathuria** [comment]
@npeltier Could you update the test URLs?

**Comment by afmicka** [comment]
@npeltier the catalog page seems broken on this branch. Could you please take a look? 
https://mwpw-157468--cc--npeltier.hlx.page/products/catalog
Screenshot 2024-09-05 at 12 23 22

**Comment by npeltier** [comment]
thanks @afmicka ! looks unrelated to my change but concerning, having a look

**Comment by npeltier** [comment]
looks it's "just" a cache issue, quotes are here because i have troubles invalidating it

**Comment by npeltier** [comment]
works better now @afmicka

**Pull request merged**
